name: build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone and Patch
        run: |
          git clone -b "${github.ref_name}-ee" --depth=1 https://gitlab.com/gitlab-org/omnibus-gitlab.git
          bash patch-dockerfile.sh

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: omnibus-gitlab/docker
          push: true
          tags: ghcr.io/x2ox/gitlab-db:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
