name: build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone and Patch
        id: meta
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
        run: |
          git clone -b "${GITHUB_REF:11}+ee.0" --depth=1 https://gitlab.com/gitlab-org/omnibus-gitlab.git
          bash patch-dockerfile.sh
          cat omnibus-gitlab/docker/Dockerfile
          cat omnibus-gitlab/docker/RELEASE
          deno run -A gen-tags.ts >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: omnibus-gitlab/docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
