name: Check
on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Version
        run: |
          bash parse-version.sh && cat version.list

      - uses: actions/github-script@v6
        with:
          script: |
            const tags = [];
            
            let tagIdx = 1;
            while (true) {
              const data = await github.rest.repos.listTags({
                owner:context.repo.owner, repo: context.repo.repo,
                page:tagIdx,per_page:100,
              })
              
              if (data.length ===0) break;
              
              tags.push(data)
            }
            
            console.log(tags)
