name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Version
        run: |
          bash parse-version.sh && cat version.list
