name: Check
on:
  push:
    branches:
      - mx

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Version
        run: |
          bash parse-version.sh && cat version.list
