name: Check
on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          path: |
            ~/.deno
            ~/.cache/deno

      - name: Check Version
        run: deno run -A main.ts
